<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Utsushi.ReportDefinition.Tests</RootNamespace>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Utsushi.ReportDefinition\Utsushi.ReportDefinition.csproj" />
  </ItemGroup>

</Project>
