<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Utsushi.Parsing.Tests</RootNamespace>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Utsushi.Parsing\Utsushi.Parsing.csproj" />
    <ProjectReference Include="..\Utsushi.TestSupport\Utsushi.TestSupport.csproj" />
  </ItemGroup>

</Project>
