<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Utsushi.Rendering.Tests</RootNamespace>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Utsushi.Rendering\Utsushi.Rendering.csproj" />
  </ItemGroup>

</Project>
